### ISSUE TITLE
Replacing functional notation not possible

### ISSUE THREAD

**Issue by asos-tomp** [stipsan/postcss-custom-properties-fallback#54]
Firstly, thanks for a great plugin!

I've noticed a problem trying to replace properties with comma-separated strings (in my use-case, some [functional notation](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgba()#values)), in that I think this plugin only supports single [postcss word nodes](https://github.com/TrySound/postcss-value-parser#word), or only ones separated by spaces, as the fallback argument.

I think this may be a similar issue to https://github.com/stipsan/postcss-custom-properties-fallback/issues/45

This unit test fails:
```javascript
tap.test('plugin() - rgba', async (t) => {
  const rgba = `
    .test {
      color: rbga(var(--color-rgb), 0.5);
    }
  `;
  const { css } = await postcss(
    plugin({
      importFrom: {
        customProperties: { '--color-rgb': '45,45,45' },
      },
    })
  ).process(rgba, { from: undefined });

  t.matchSnapshot(clean(css), 'functional notation example');
  t.end();
});
```
...this produces a snapshot:
```javascript
exports[`test/plugin.mjs TAP plugin() - rgba > functional notation example 1`] = `

    .test {
      color: rbga(var(--color-rgb,45,,,45,,,45), 0.5);
    }
  
`
```
...but would expect:
```javascript
exports[`test/plugin.mjs TAP plugin() - rgba > functional notation example 1`] = `

    .test {
      color: rbga(var(--color-rgb,45,45,45), 0.5);
    }
  
`
```
The issue appears to be the `parse` [that has been done on the values](https://github.com/stipsan/postcss-custom-properties-fallback/blob/main/src/import-from.js#L25) in the provided config; I am unclear what the `parse` achieves:
```javascript
function getCustomPropertiesFromObject(object) {
  const customProperties = Object.assign(
    {},
    Object(object).customProperties,
    Object(object)['custom-properties']
  );

  for (const key in customProperties) {
    customProperties[key] = parse(String(customProperties[key])).nodes;
  }

  return customProperties;
}
```
..because when removing that, to become:
```javascript
function getCustomPropertiesFromObject(object) {
  const customProperties = Object.assign(
    {},
    Object(object).customProperties,
    Object(object)['custom-properties']
  );

  return customProperties;
}
```
...the existing unit tests (and the new one above) seem to pass.

Interestingly, using a [css4 space-separated notation](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgba()#space-separated_values) rather than commas seems to work - so I can get the following snapshot OK:
```javascript
exports[`test/plugin.mjs TAP plugin() - rgba > functional notation example 2`] = `

    .test {
      color: rbga(var(--color-rgb,45 45 45) / 0.5);
    }
  
`
```
But I would like to support Safari 12.0, which doesn't yet support that notation.

**Comment by stipsan** [comment]
Fixed in [v1.0.2](https://github.com/stipsan/postcss-custom-properties-fallback/releases/tag/v1.0.2) 🎉
